---
- name: "Gather EC2 facts"
  ec2_metadata_facts:

- name: "Create awslogs config for {{ app.name }}"
  template:
    src: log_conf.j2
    dest: /etc/awslogs/config/{{ app.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart awslogs
