---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: CMS-AWS-West-ansible-role-app-cloudwatch-logs
      vars:
        app:
          name: test-app
          logs:
            - file: /var/log/test_app.log
